/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TasktifierGUI;

import java.awt.*;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class Admin extends javax.swing.JFrame {
    private static Admin instance;
    /**
     * Creates new form Admin
     */
    public Admin() {
        user.SQLMethods method = new user.SQLMethods();
        int[] userIDs = method.readUserIDs();
        
        this.setUndecorated(true);
        
        initComponents();
        
        try {
            java.util.List<Object[]> usersData = method.readUsersList();

            Object[][] usersArray = new Object[usersData.size()][];
            usersData.toArray(usersArray);

            DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                    usersArray,
                    new String[]{"ID", "Email", "Status", "Action"}
            );

            UsersTable.setModel(model);

        } catch (SQLException e) {}
        
        customComponents.AdminTableActionEvent event = new customComponents.AdminTableActionEvent(){
            @Override
            public void updateUser(int row){
                new popupFrame.UpdateUser(userIDs[row]).setVisible(true);
            }
            @Override
            public void deleteUser(int row){
                if(TasktifierGUI.Index.getAdminInstance() != null){
                    TasktifierGUI.Index.getAdminInstance().dispose();
                }
                Admin.getInstance().dispose();
                method.deleteUserByID(userIDs[row]);
            }
            @Override
            public void changeUserStatus(int row){
                if(TasktifierGUI.Index.getAdminInstance() != null){
                    TasktifierGUI.Index.getAdminInstance().dispose();
                }
                Admin.getInstance().dispose();
                method.updateUserStatus(userIDs[row]);
            }
        };
        
        UsersTable.getColumnModel().getColumn(3).setCellRenderer(new customComponents.AdminTableActionCellRender());
        UsersTable.getColumnModel().getColumn(3).setCellEditor(new customComponents.AdminTableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPanelHeader = new javax.swing.JPanel();
        FirstCircle = new customComponents.Circles(255, 95, 87);
        SecondCircle = new customComponents.Circles(255, 189, 41);
        ThirdCircle = new customComponents.Circles(38, 202, 63);
        LogoutButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        MinimizeButton = new javax.swing.JButton();
        ThemeChangeButton = new javax.swing.JButton();
        customComponents.RoundedPanel roundedPanel = new customComponents.RoundedPanel(10);
        AdminPanelContainer = new javax.swing.JPanel();
        AdminInterface = new javax.swing.JScrollPane();
        UsersList = new javax.swing.JPanel();
        UsersListLabel = new javax.swing.JLabel();
        UsersScrollPane = new javax.swing.JScrollPane();
        UsersTable = new customComponents.AdminTableDarkStatus();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1065, 782));
        setResizable(false);

        AdminPanelHeader.setBackground(new java.awt.Color(26, 36, 33));

        FirstCircle.setBackground(new java.awt.Color(26, 36, 33));

        javax.swing.GroupLayout FirstCircleLayout = new javax.swing.GroupLayout(FirstCircle);
        FirstCircle.setLayout(FirstCircleLayout);
        FirstCircleLayout.setHorizontalGroup(
            FirstCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        FirstCircleLayout.setVerticalGroup(
            FirstCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        SecondCircle.setBackground(new java.awt.Color(26, 36, 33));

        javax.swing.GroupLayout SecondCircleLayout = new javax.swing.GroupLayout(SecondCircle);
        SecondCircle.setLayout(SecondCircleLayout);
        SecondCircleLayout.setHorizontalGroup(
            SecondCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        SecondCircleLayout.setVerticalGroup(
            SecondCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ThirdCircle.setBackground(new java.awt.Color(26, 36, 33));

        javax.swing.GroupLayout ThirdCircleLayout = new javax.swing.GroupLayout(ThirdCircle);
        ThirdCircle.setLayout(ThirdCircleLayout);
        ThirdCircleLayout.setHorizontalGroup(
            ThirdCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        ThirdCircleLayout.setVerticalGroup(
            ThirdCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LogoutButton.setBackground(new java.awt.Color(26, 36, 33));
        LogoutButton.setForeground(new java.awt.Color(217, 217, 217));
        LogoutButton.setText("↪");
        LogoutButton.setBorderPainted(false);
        LogoutButton.setFocusPainted(false);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(26, 36, 33));
        ExitButton.setForeground(new java.awt.Color(217, 217, 217));
        ExitButton.setText("✖");
        ExitButton.setBorderPainted(false);
        ExitButton.setFocusPainted(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        MinimizeButton.setBackground(new java.awt.Color(26, 36, 33));
        MinimizeButton.setForeground(new java.awt.Color(217, 217, 217));
        MinimizeButton.setText("➖");
        MinimizeButton.setBorderPainted(false);
        MinimizeButton.setFocusPainted(false);
        MinimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonActionPerformed(evt);
            }
        });

        ThemeChangeButton.setBackground(new java.awt.Color(51, 67, 62));
        ThemeChangeButton.setForeground(new java.awt.Color(217, 217, 217));
        ThemeChangeButton.setBorderPainted(false);
        ThemeChangeButton.setFocusPainted(false);

        javax.swing.GroupLayout AdminPanelHeaderLayout = new javax.swing.GroupLayout(AdminPanelHeader);
        AdminPanelHeader.setLayout(AdminPanelHeaderLayout);
        AdminPanelHeaderLayout.setHorizontalGroup(
            AdminPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SecondCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ThirdCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThemeChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(MinimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        AdminPanelHeaderLayout.setVerticalGroup(
            AdminPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelHeaderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(AdminPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelHeaderLayout.createSequentialGroup()
                        .addGroup(AdminPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SecondCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThirdCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MinimizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(AdminPanelHeaderLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(ThemeChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        AdminPanelContainer.setBackground(new java.awt.Color(21, 28, 26));
        AdminPanelContainer.setVisible(true);

        AdminInterface.setBackground(new java.awt.Color(21, 28, 26));
        AdminInterface.setBorder(null);
        AdminInterface.setOpaque(false);
        JViewport Viewport = AdminInterface.getViewport();

        Viewport.setBackground(new Color(21, 28, 26));

        AdminInterface.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        UsersList.setBackground(new java.awt.Color(21, 28, 26));

        UsersListLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UsersListLabel.setForeground(new java.awt.Color(51, 153, 255));
        UsersListLabel.setText("ADMIN PANEL");

        UsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Email", "Status", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UsersTable.setFocusable(false);
        UsersTable.getTableHeader().setReorderingAllowed(false);
        UsersScrollPane.setViewportView(UsersTable);

        javax.swing.GroupLayout UsersListLayout = new javax.swing.GroupLayout(UsersList);
        UsersList.setLayout(UsersListLayout);
        UsersListLayout.setHorizontalGroup(
            UsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsersScrollPane)
                    .addGroup(UsersListLayout.createSequentialGroup()
                        .addComponent(UsersListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 592, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UsersListLayout.setVerticalGroup(
            UsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersListLayout.createSequentialGroup()
                .addComponent(UsersListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminInterface.setViewportView(UsersList);

        javax.swing.GroupLayout AdminPanelContainerLayout = new javax.swing.GroupLayout(AdminPanelContainer);
        AdminPanelContainer.setLayout(AdminPanelContainerLayout);
        AdminPanelContainerLayout.setHorizontalGroup(
            AdminPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelContainerLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(AdminInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        AdminPanelContainerLayout.setVerticalGroup(
            AdminPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelContainerLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(AdminInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static Admin getInstance() {
        if (instance == null) {
            instance = new Admin();
        }
        return instance;
    }
    
    private void MinimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Exit Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {
            user.Authenticator authenticator = new user.Authenticator();
            int loggedInID = authenticator.getLoggedInUserID();
            authenticator.updateLoginStatus(loggedInID, false);
            setVisible(false);
            dispose();
            Login loginFrame = Login.getInstance();
            SwingUtilities.invokeLater(() -> {
                loginFrame.setVisible(true);
            });
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AdminInterface;
    private javax.swing.JPanel AdminPanelContainer;
    private javax.swing.JPanel AdminPanelHeader;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel FirstCircle;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MinimizeButton;
    private javax.swing.JPanel SecondCircle;
    private javax.swing.JButton ThemeChangeButton;
    private javax.swing.JPanel ThirdCircle;
    private javax.swing.JPanel UsersList;
    private javax.swing.JLabel UsersListLabel;
    private javax.swing.JScrollPane UsersScrollPane;
    private customComponents.AdminTableDarkStatus UsersTable;
    // End of variables declaration//GEN-END:variables
}
