/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package popupFrame;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Daniel
 */
public class StartTimeReminderFrame extends javax.swing.JFrame {
    static {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {}
    }
    /**
     * Creates new form ReminderFrame
     * @param task_name
     * @param notes
     */
    public StartTimeReminderFrame(String task_name, String notes) {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        int x = screenSize.width - this.getWidth();
        int y = 0;
        
        TaskNameTextField.setText(task_name);
        NotesTextArea.setText(notes);
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReminderFrameHeader = new javax.swing.JPanel();
        FirstCircle = new customComponents.Circles(255, 95, 87);
        SecondCircle = new customComponents.Circles(255, 189, 41);
        ThirdCircle = new customComponents.Circles(38, 202, 63);
        ExitButton = new javax.swing.JButton();
        ReminderFrameContainer = new javax.swing.JPanel();
        DontForgetLabel = new javax.swing.JLabel();
        LabelDetailsSeparator = new javax.swing.JSeparator();
        TaskNameTextField = new javax.swing.JTextField();
        NotesScrollPane = new javax.swing.JScrollPane();
        NotesTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ReminderFrameHeader.setBackground(new java.awt.Color(26, 36, 33));

        FirstCircle.setBackground(new java.awt.Color(26, 36, 33));

        javax.swing.GroupLayout FirstCircleLayout = new javax.swing.GroupLayout(FirstCircle);
        FirstCircle.setLayout(FirstCircleLayout);
        FirstCircleLayout.setHorizontalGroup(
            FirstCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        FirstCircleLayout.setVerticalGroup(
            FirstCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        SecondCircle.setBackground(new java.awt.Color(26, 36, 33));

        javax.swing.GroupLayout SecondCircleLayout = new javax.swing.GroupLayout(SecondCircle);
        SecondCircle.setLayout(SecondCircleLayout);
        SecondCircleLayout.setHorizontalGroup(
            SecondCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        SecondCircleLayout.setVerticalGroup(
            SecondCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ThirdCircle.setBackground(new java.awt.Color(26, 36, 33));

        javax.swing.GroupLayout ThirdCircleLayout = new javax.swing.GroupLayout(ThirdCircle);
        ThirdCircle.setLayout(ThirdCircleLayout);
        ThirdCircleLayout.setHorizontalGroup(
            ThirdCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        ThirdCircleLayout.setVerticalGroup(
            ThirdCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ExitButton.setBackground(new java.awt.Color(26, 36, 33));
        ExitButton.setForeground(new java.awt.Color(217, 217, 217));
        ExitButton.setText("✖");
        ExitButton.setBorderPainted(false);
        ExitButton.setFocusPainted(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReminderFrameHeaderLayout = new javax.swing.GroupLayout(ReminderFrameHeader);
        ReminderFrameHeader.setLayout(ReminderFrameHeaderLayout);
        ReminderFrameHeaderLayout.setHorizontalGroup(
            ReminderFrameHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReminderFrameHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SecondCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ThirdCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ReminderFrameHeaderLayout.setVerticalGroup(
            ReminderFrameHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReminderFrameHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReminderFrameHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SecondCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThirdCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        ReminderFrameContainer.setBackground(new java.awt.Color(21, 28, 26));

        DontForgetLabel.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        DontForgetLabel.setForeground(new java.awt.Color(255, 255, 255));
        DontForgetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DontForgetLabel.setText("It's time to start your task today!");

        TaskNameTextField.setEditable(false);
        TaskNameTextField.setBackground(new java.awt.Color(21, 28, 26));
        TaskNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TaskNameTextField.setForeground(new java.awt.Color(102, 255, 0));
        TaskNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TaskNameTextField.setText("Eating Bee Lots");
        TaskNameTextField.setBorder(null);

        NotesScrollPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 51, 47), 1, true));

        NotesTextArea.setBackground(new java.awt.Color(21, 28, 26));
        NotesTextArea.setColumns(20);
        NotesTextArea.setForeground(new java.awt.Color(217, 217, 217));
        NotesTextArea.setRows(5);
        NotesTextArea.setText("Eat a lot of bee lots because it's rich in vitamins and minerals.");
        NotesTextArea.setLineWrap(true);
        NotesTextArea.setWrapStyleWord(true);
        NotesScrollPane.setViewportView(NotesTextArea);

        javax.swing.GroupLayout ReminderFrameContainerLayout = new javax.swing.GroupLayout(ReminderFrameContainer);
        ReminderFrameContainer.setLayout(ReminderFrameContainerLayout);
        ReminderFrameContainerLayout.setHorizontalGroup(
            ReminderFrameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReminderFrameContainerLayout.createSequentialGroup()
                .addGroup(ReminderFrameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReminderFrameContainerLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(ReminderFrameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelDetailsSeparator)
                            .addComponent(TaskNameTextField)
                            .addComponent(NotesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                    .addGroup(ReminderFrameContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DontForgetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ReminderFrameContainerLayout.setVerticalGroup(
            ReminderFrameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReminderFrameContainerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(DontForgetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelDetailsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TaskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NotesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReminderFrameHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ReminderFrameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ReminderFrameHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ReminderFrameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        try{
//            UIManager.setLookAndFeel(new FlatDarkLaf());
//        } catch (UnsupportedLookAndFeelException e){}
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReminderFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DontForgetLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel FirstCircle;
    private javax.swing.JSeparator LabelDetailsSeparator;
    private javax.swing.JScrollPane NotesScrollPane;
    private javax.swing.JTextArea NotesTextArea;
    private javax.swing.JPanel ReminderFrameContainer;
    private javax.swing.JPanel ReminderFrameHeader;
    private javax.swing.JPanel SecondCircle;
    private javax.swing.JTextField TaskNameTextField;
    private javax.swing.JPanel ThirdCircle;
    // End of variables declaration//GEN-END:variables
}
